const universities = [
  "Cairo University",
  "Alexandria University",
  "Ain Shams University",
  "Mansoura University",
  "Assiut University",
  "Helwan University",
  "Zagazig University",
  "Tanta University",
  "Suez Canal University",
  "Minia University",
  "Beni-Suef University",
  "Fayoum University",
  "Sohag University",
  "Aswan University",
  "Damietta University",
  "Port Said University",
  "Suez University",
  "Damanhour University",
  "Kafrelsheikh University",
  "South Valley University",
  "Al-Azhar University",
  "Zewail City of Science, Technology and Innovation",
  "King Salman International University",
  "Galala University",
  "Alamein International University",
  "New Mansoura University",
  "Egypt University of Informatics",
  "The American University in Cairo (AUC)",
  "German University in Cairo (GUC)",
  "British University in Egypt (BUE)",
  "Misr International University (MIU)",
  "Modern Sciences and Arts University (MSA)",
  "October 6 University",
  "Future University in Egypt (FUE)",
  "Pharos University in Alexandria (PUA)",
  "Canadian International College (CIC)",
  "Arab Academy for Science, Technology and Maritime Transport (AASTMT)",
  "Egyptian Russian University (ERU)",
  "Sinai University",
  "Nahda University in Beni Suef (NUB)",
  "New Giza University (NGU)",
  "Horus University - Egypt (HUE)",
  "European Universities in Egypt (EUE)",
  "University of Hertfordshire in Egypt",
  "Toronto Metropolitan University Cairo",
  "Université Française d'Égypte (UFE)",
  "ESLSCA University",
];

export default universities;
